# Generated by Django 6.1 on 2026-08-27 20:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_book_created_at_book_categories_userbook_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userbook',
            unique_together={('user', 'book')},
        ),
    ]
